### ISSUE TITLE
use-selected-layout-segment.mdx

### ISSUE THREAD

**Issue by ChanghyeonYoon** [Nextjs-kr/Nextjs.kr#101]
@SeongsangCHO

**Comment by ChanghyeonYoon** [comment]
@SeongsangCHO 많은 분들의 참여를 위해 1인 1개로 제한하고 있는 점 양해 부탁드립니다.

**Comment by ChanghyeonYoon** [comment]
@SeongsangCHO 이슈 할당 후 1주일 경과됐습니다, 작업 진행 부탁드립니다!

**Comment by SeongsangCHO** [comment]
@ChanghyeonYoon 알림을 드려야하는군요 ~ PR Open되어있습니다 !
https://github.com/Nextjs-kr/Nextjs.kr/pull/269

**Comment by yoo-jimin127** [comment]
closed by #269
