### ISSUE TITLE
redirect.mdx

### ISSUE THREAD

**Issue by ChanghyeonYoon** [Nextjs-kr/Nextjs.kr#116]
@baegofda

**Comment by ChanghyeonYoon** [comment]
@baegofda 이슈 할당 후 1주일 경과됐습니다, 작업 진행 부탁드립니다!

**Comment by baegofda** [comment]
@ChanghyeonYoon  아ㅠㅠ 갑자기 회사 프로젝트가 바빠져서 지금 시작합니다!
