### ISSUE TITLE
turbopack.mdx

### ISSUE THREAD

**Issue by ChanghyeonYoon** [Nextjs-kr/Nextjs.kr#135]
@bro-jo

**Comment by ChanghyeonYoon** [comment]
@bro-jo 이슈 할당 후 1주일 경과됐습니다, 작업 진행 부탁드립니다!

**Comment by bro-jo** [comment]
제가 1주일 기한을 놓치고 있었네요 죄송합니다 🙏 
https://github.com/Nextjs-kr/Nextjs.kr/pull/359
PR 올렸습니다~~
괜찮다면 하나더 진행해보고 싶네요 :)
