### ISSUE TITLE
link.mdx

### ISSUE THREAD

**Issue by ChanghyeonYoon** [Nextjs-kr/Nextjs.kr#198]
@oy-kkddgg1001

**Comment by deokgoo** [comment]
@ChanghyeonYoon  안녕하세요
번역시작하겠습니다 

죄송하지만 멘션 및 아이디 변경드려도 괜찮을까요? 🙇 
현재 아이디로... @oy-kkddgg1001 => @deokgoo

**Comment by deokgoo** [comment]
https://github.com/Nextjs-kr/Nextjs.kr/pull/235

**Comment by ChanghyeonYoon** [comment]
closed by #235
