### ISSUE TITLE
redirects.mdx

### ISSUE THREAD

**Issue by ChanghyeonYoon** [Nextjs-kr/Nextjs.kr#203]
@HA-SEUNG-JEONG

**Comment by HA-SEUNG-JEONG** [comment]
@ChanghyeonYoon 작업 시작하겠습니다~

**Comment by HA-SEUNG-JEONG** [comment]
<a href='https://github.com/Nextjs-kr/Nextjs.kr/pull/234'>#234 </a>
작업 완료했습니다!

**Comment by ChanghyeonYoon** [comment]
closed by #234
