### ISSUE TITLE
pageExtensions.mdx

### ISSUE THREAD

**Issue by ChanghyeonYoon** [Nextjs-kr/Nextjs.kr#217]
@p-acid

**Comment by ChanghyeonYoon** [comment]
@p-acid 다양한 분들의 참여를 위해 1인 1개로 제한하는 점 양해 부탁드립니다!

**Comment by p-acid** [comment]
@ChanghyeonYoon 작업 시작했습니다!

그리고 공유 페이지에 대한 안내를 확인했는데 이해가 되지 않는 부분이 있어 질문 사항이 있어 이렇게 질문드립니다.

현재 `pageExtensions` 파트의 경우 페이지 라우터 부분이 전부 앱 라우터 디렉토리 내 `pageExtensions.mdx` 에 위치했는데, 이 경우엔 메타데이터만 번역을 진행함이 맞는지 여쭤보고 싶습니다. 

![스크린샷 2023-06-27 오전 9 02 41](https://github.com/Nextjs-kr/Nextjs.kr/assets/87939521/19695dea-f4c9-45cd-8043-c10cab40a7f6)

추가적으로 혹시 빠르게 작업이 마무리가 되었다면 추가 번역을 진행할 수 있는지 여쭤보고 싶습니다!

**Comment by YuriKwon** [comment]
closed by https://github.com/Nextjs-kr/Nextjs.kr/pull/282
