### ISSUE TITLE
runtime-configuration.mdx

### ISSUE THREAD

**Issue by ChanghyeonYoon** [Nextjs-kr/Nextjs.kr#223]
@DohwanKim

**Comment by DohwanKim** [comment]
@ChanghyeonYoon 
번역 시작하겠습니다. :)


질문이 있어 추가로 글을 남깁니다.

제가 번역을 맡게 될 `03-pages/02-api-reference/03-next-config-js/runtime-configuration.mdx` 의 경우 
`02-app/02-api-reference/05-next-config-js/runtime-configuration.mdx`를 soruce로 공유하여 출력하고 있습니다.

이 경우 `02-app/02-api-reference/05-next-config-js/runtime-configuration.mdx`를 번역하고 soruce로 연결 시켜 출력해야 할까요?
중복 번역으로 이어 질 수도 있는 부분인거 같은데 혹시 확인되신 사항인지 궁금합니다!!

**Comment by ChanghyeonYoon** [comment]
번역해주시면 제가 동시 할당 해놓겠습니다!
