### ISSUE TITLE
get-initial-props.mdx

### ISSUE THREAD

**Issue by ChanghyeonYoon** [Nextjs-kr/Nextjs.kr#29]
@gunwooko

**Comment by ChanghyeonYoon** [comment]
@gunwooko 이슈 할당 후 1주일 경과됐습니다, 작업 진행 부탁드립니다!

**Comment by gunwooko** [comment]
@ChanghyeonYoon 작업 시작했습니다!

**Comment by gunwooko** [comment]
PR 남겼습니다~ https://github.com/Nextjs-kr/Nextjs.kr/pull/318
