### ISSUE TITLE
use-router.mdx

### ISSUE THREAD

**Issue by ChanghyeonYoon** [Nextjs-kr/Nextjs.kr#64]
@synuns

**Comment by ChanghyeonYoon** [comment]
@synuns 이슈 할당 후 1주일 경과됐습니다, 작업 진행 부탁드립니다!

**Comment by synuns** [comment]
@ChanghyeonYoon 이슈에 안남기고 초안작성했네요 ㅠ
작업시작했습니다!

**Comment by synuns** [comment]
@ChanghyeonYoon  @chaejunlee 첫번째 리뷰 이후에 2주가 넘게 지났는데 리뷰 우선적으로 부탁드리겠습니다
